language: java

sudo: enabled

env:
  global:
    - secure: "XaacpPCZUBAjKvJgj+TVpzsTGJxV4UgiSaaVVyof6scAv1CUAAl1sly1OIlCbKQkufsvNJGBllaiLOC8BDZEjkZvLhRqqntOFJDxKzn2hpvz9tfZF4AzYEAIBk8eGLKGgBVIXbHbmgPXXDSx5BLVBmhXiXACTPSfcDbFlxnbjwgH1xbYFEdErtytjO1zhuXNlwo0AMYcgJ/djqRK3u0YTuRVicX/8QIHmS+/P/1l76IQNsB8hZcSjlphMvCq7h9JxpNj4rE0JOMkA6bdmLR93sdughpgChiYhyVPaKByjmSopOT9Kowy6Y3JahEug/AZVhyaMjkrhjs+ru/t/U0sWbdC1OLfYW49CqbscgvUSwBrqXsOwCetN/pMy5tndy+7HoafMjowtsrtXrVDn87Wam07VUj6hv0tUKMNUObBYYNpuNT2V8/GLuyoMaTtPE9sdr9PsBsVxnA/S+sLv63qw9B8hK6MJbvVxVKm0kMfWG0enAYE3SsdMiPlkWECCgAvSWkArgWRSGLcdKu4nDH16fIQiR6KXmNdW2ifSs++L1CobxOiqt+Mrkhx+moCe4ITs7yRRlptjjki5x3/dv3OFHs30tosZbo7Kh1xSnzEeNrMhnGfHEznGW3azA8GPxYf+Xe8aTX7foAF8j/KCOR6VcQDam5IJ39qh9FoxM29LX4="

os:
  - linux

jdk:
  - oraclejdk8

install:
  - chmod +x gradlew

script:
  - ./gradlew clean fatJar dependencyCheckAnalyze
