name: NightBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 12, 13, 14]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle For JDK ${{ matrix.java }}
      run: ./gradlew clean fatJar dependencyCheckAnalyze
    - uses: actions/upload-artifact@v1
      with:
        name: NightBuild-JDK-${{ matrix.java }}
        path: build/libs/LogRequestsToSQLite.jar
