name: NightBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        architecture: x64
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean fatJar dependencyCheckAnalyze
    - uses: actions/upload-artifact@v1
      with:
        name: LogRequestsToSQLite-NightBuild.jar
        path: build/libs/LogRequestsToSQLite.jar
